name: amp
description: "Aurio - A modern music player."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  share_plus: ^10.1.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/aurio.png
    - images/aurio_padded.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/aurio_padded.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/aurio_padded.png"
